<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Jayarees-MacBook-Pro.local" name="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice" tests="6" failures="0" timestamp="19 Nov 2019 16:30:50 GMT" time="32.296" errors="1">
  <testcase name="finish_notice_appears" time="0.012" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Elements.Popbitch_Finish_Notice_elements.Verify_finish_notice_appears(Popbitch_Finish_Notice_elements.java:86)
at Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice.finish_notice_appears(POPSMO01_Popbitch_register_from_first_use_notice.java:134)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- finish_notice_appears -->
  <testcase name="i_am_a_user_of_Axate_and_I_am_on_the_registration_page_through_popbitch_FUN" time="6.326" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice"/>
  <testcase name="i_enter_all_the_required_details_on_step_one_and_click_on_continue" time="13.332" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice"/>
  <testcase name="top_up_with_a_valid_card_in_steptwo_with_one_pound_and_click_on_continue" time="3.742" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice"/>
  <testcase name="i_get_a_funded_axate_wallet_with_one_pound_in_it" time="8.878" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice"/>
  <testcase name="navigated_to_the_same_article" time="0.006" classname="Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice"/>
</testsuite> <!-- Stepdef.Popbitch.POPSMO01_Popbitch_register_from_first_use_notice -->
